services:
    api:
        image: api
        build:
            context: .
            dockerfile: API/Dockerfile
        container_name: todoer-api
        depends_on:
            - db
        ports:
            - 5001:443        
        environment:
            - DOTNET_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_Kestrel__Certificates__Default__Password=todoerlocal
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        volumes:
            - ~/.aspnet/https:/https:ro
    db:
        image: postgres:16-alpine
        restart: always
        env_file:
            - db-variables.env
        ports:
            - 5432:5432
        volumes:
            - db-data:/var/lib/postgresql/data
            
volumes:
    db-data: { }
