services:
    api:
        image: api
        build:
            context: .
            dockerfile: API/Dockerfile
        container_name: todoer-api
        depends_on:
            - db
        ports:
            - 5001:443
        env_file:
            - api-variables.env
        volumes:
            - ~/.aspnet/https:/https:ro
    db:
        image: postgres:16-alpine
        restart: always
        env_file:
            - db-variables.env
        ports:
            - 5432:5432
        volumes:
            - db-data:/var/lib/postgresql/data
    redis:
        image: redis:7-alpine
        restart: always
        ports:
            - 6379:6379
volumes:
    db-data: { }
